### ISSUE TITLE
UNTRUSTED signature

### ISSUE THREAD

**Issue by RadekSoltys** [sgerrand/alpine-pkg-node-bower#4]
I'm persistently getting the error "UNTRUSTED signature" on "apk add node-bower-1.8.0-r0.apk".
(npm working fine.)
[alpine-virt-3.6.2-x86_64)

**Comment by sgerrand** [comment]
Are you able to provide an example Dockerfile for this error? I suspect
that you may not have added the public key used to sign the package, prior
to adding the node-bower package.

**Comment by RadekSoltys** [comment]
Sorry, it's not in Docker.
I followed your recipe and
ls /etc/apk/keys
lists
sgerrand.rsa.pub
thanks for this quick response, let me know how I can help.

**Comment by sgerrand** [comment]
@RadekSoltys: I've tested installation using the following Dockerfile and can't reproduce your error.
```
FROM alpine:3.6
RUN apk --no-cache add ca-certificates nodejs wget && \
    wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://raw.githubusercontent.com/sgerrand/alpine-pkg-node-bower/master/sgerrand.rsa.pub && \
    wget https://github.com/sgerrand/alpine-pkg-node-bower/releases/download/1.8.0-r0/node-bower-1.8.0-r0.apk && \
    apk add node-bower-1.8.0-r0.apk
```
Would you please provide the output from `apk add node-bower-1.8.0-r0.apk` so that I can debug your issue further.

**Comment by RadekSoltys** [comment]
I executed the commands manually, which yielded the following message:
ERROR: node-bower-1.8.0-r0.apk UNTRUSTED signature

Meanwhile I installed bower using npm, so it's not a big problem for me anymore.

I understand that this is working for everyone else, so we could leave it there for now.

I will be going off, but I could test this again with docker next month.

Many thanks for your support

**Comment by sgerrand** [comment]
The important thing to do is import my public signing key:
```
wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://raw.githubusercontent.com/sgerrand/alpine-pkg-node-bower/master/sgerrand.rsa.pub
```
If you don't do that then `apk add` will emit the warning you encountered.
